/**
* URL - https://projecteuler.net/problem=2
*/
#include <iostream>

int main(int argc, char* argv[]) {
    std::uint64_t sum = 0;
    const std::uint64_t limit = 4000000;

    /**
    * Each new term in the Fibonacci sequence is generated by sum the previous two terms.
    * By starting with 1 and 2, next terms can be found as:
    * tmp <- a (Save value of 'a' variable in temporary variable)
    * a <- b
    * b <- tmp + b
    */

    for (std::uint64_t a = 1, b = 2, tmp = 0; a < limit; tmp = a, a = b, b += tmp) 
        if (!(a & 1))
            sum += a;
    std::cout << sum << '\n';
    
    return 0;
}